### ISSUE TITLE
Cannot install in Scientific Linux 6

### ISSUE THREAD

**Issue by anusornl** [AravisProject/aravis#134]
I want to install Aravis for my usb camera, but I have missing libraries such as
•gobject-2.0
•gio-2.0
•gthread-2.0
•libusb-1.0
•librsb-1.0.0-dev
•libgstreamer1.0-dev
•libgstreamer1.0-dev
•libgstreamer-plugins-base1.0-dev
•gtk+-3.0 &gt;=3.12

When I try ./configure --enable-gst-plugin, I also have error lines
configure: error: No package 'gstreamer-base-1.0' found
No package 'gstreamer-app-1.0' found - Can not build gstreamer plugin

Please help.

**Comment by EmmanuelP** [comment]
SL6 is an old distribution, which means glib/gtk/gstreamer packages are old too. You have to install the requirements manually by compiling them using the released tarballs.

In order to not mess with the distribution versions, I suggest you to install them in a dedicated path, like /opt/aravis, using the configure --prefix option:
```
configure --prefix /opt/aravis
```
and setting the PKG_CONFIG_PATH environment:
```
export PKG_CONFIG_PATH=/opt/aravis/lib/pkgconfig
```
Do you really have to use SL6 ? Installing aravis dependencies is a long and tedious task, especially GStreamer. It would be easier to use a recent distribution like fedora or ubuntu.
