### ISSUE TITLE
Need for a USB device handle accessor

### ISSUE THREAD

**Issue by ChaosCA** [AravisProject/aravis#166]
Currently Aravis will automatically latch onto USB cameras it can. This creates an issue for some cameras where I use the manufacturer API as their API can't get access from Aravis.

Is there a way to prevent Aravis from automatically capturing cameras?

**Comment by EmmanuelP** [comment]
The USB device is just kept open by aravis, because it would not be good performance wise to open/close it at each access, especially during the streaming.

What could be done would be to add a libusb_device_handle accessor. What does the vendor API look lilke ? Is there a way to give it an already open USB device handle ?

**Comment by ChaosCA** [comment]
Even recompiling with USB Support disabled in aravis hasn't seemed to fix the issue..

**Comment by ChaosCA** [comment]
I've sent a message to Point Grey in that case and will get back to you. It seems to me like it doesn't play nicely with Aravis installed however.

Using multiprocessing to connect to different cameras using their API while Aravis handles GigE cameras has been failing. The USB side of things doesn't seem to allow more than one synchronous connection and I figured aravis might be causing the issue.

**Comment by ChaosCA** [comment]
It wasn't Aravis' fault. Sorry for the issue.
Point Grey is looking into it.

Thanks @EmmanuelP
