### ISSUE TITLE
MultiFrame and pixel format: 0x0

### ISSUE THREAD

**Issue by 8djudju8** [AravisProject/aravis#194]
When using a emergent HS-2000M camera with the feature AcquisitionMode=MultiFrame set
arv-viewer 0.6 does not show the stream and print this message:
Aravis-Message: GStreamer cannot understand the camera pixel format: 0x0!

**Comment by EmmanuelP** [comment]
Please attach the output of `arv-viewer --debug=all:3`

**Comment by EmmanuelP** [comment]
It looks like at some point the camera is too long to answer to a command, and the acknowledge is received after the timeout. On the next try, aravis receives the acknowledge of the previous command. We should flush the incoming packets with an id lower than the current one.

**Comment by EmmanuelP** [comment]
Well, a flush mechanism is already in place. Before sending a command, we check for incoming packets and flush them. But it looks like it is not effective with this camera, which is piling acknowledges and send them slowly.

We have to change the way Aravis is dealing with late acknowledge, and instead of flusing the incoming packets before sending a command, we should discard any incoming packets during the read packet timeout period.

**Comment by EmmanuelP** [comment]
@8djudju8 I would appreciate if you could try aravis master branch, if you are still interrested in aravis. I have just commited some fixes that should make the communication with your camera more robust.

**Comment by EmmanuelP** [comment]
I'm closing this report. Please reopen if the issue persists.

Cheers.
