### ISSUE TITLE
Weird library names with 0.7.0

### ISSUE THREAD

**Issue by lovesegfault** [AravisProject/aravis#300]
**Describe the bug**
Packaging Aravis 0.7.0 for Gentoo I came across this in  the output package:
```
❯ ls usr/lib64
Permissions  Size User         Date Modified Name
drwxr-xr-x      - lovesegfault 26 Sep  1:15  girepository-1.0/
lrwxrwxrwx     18 lovesegfault 26 Sep  1:15  libaravis-0.8.so -> libaravis-0.8.so.0
lrwxrwxrwx     22 lovesegfault 26 Sep  1:15  libaravis-0.8.so.0 -> libaravis-0.8.so.0.7.0
.rwxr-xr-x  416Ki lovesegfault 26 Sep  1:15  libaravis-0.8.so.0.7.0*
drwxr-xr-x      - lovesegfault 26 Sep  1:15  pkgconfig/
``` 

**Expected behavior**
It's weird that the lib for Aravis 0.7 is called `libaravis-0.8` and it's even weirder to have it soname'd to `0.7.0`. I'd expect it to be `libaravis-0.7`, or just `libaravis` with the `.so.0.7.0` symlink.

**Platform description:**
 - Aravis version: 0.7.0
 - OS: Gentoo
 - Hardware amd64

**Comment by EmmanuelP** [comment]
Hi,

It may seems weird, but that is what people do in order to have parallel installable versions.

0.7.x is for the release of unstable versions.
0.8 is the API version. 0.8 API will be unstable during 0.7.x serie, and stable during 0.8.x serie.

I may have gone too far by also making executables parallel installable. I may get back to executable names without suffix for the 1.0 release.

Cheers,

  Emmanuel.
