### ISSUE TITLE
Feature need: Configure or set CTI File 

### ISSUE THREAD

**Issue by garfeng** [AravisProject/aravis#661]
**Is your feature request related to a problem? Please describe.**

The manufacturer (HikRobots) provides a Gige frame grabber card. It looks like a net card.

![81965d46d38b29cb5cabe2fad97fa1b](https://user-images.githubusercontent.com/19792314/161904333-36a7d2e4-178f-4d3c-82c9-d4875dc0075f.png)

 When I connect my Gige camera from their card, the aravis can not detect it. But aravis works properly when camera is connected  to the default Ethernet. 

 HikRobots software MVS (Select CTI File) : 

![图片](https://user-images.githubusercontent.com/19792314/161888304-604d4d33-1f8c-43ac-8107-d3fbcaf3d1d9.png)

![980a5e0147c54f9eb99abf4812b08b50](https://user-images.githubusercontent.com/19792314/161887566-c128bdde-d936-487d-999d-6ebb9a2d2dca.png)

Then, the MVS detected the net card.

![图片](https://user-images.githubusercontent.com/19792314/161887794-cb4eef45-3c72-46f5-9ceb-09ce1d581d35.png)

and the camera is listed to the net card
![图片](https://user-images.githubusercontent.com/19792314/161888042-d4c061bd-c9b7-4d79-9bd2-6c7a0195268d.png)

**Describe the solution you'd like**

May you provide a api for us to set the CTI file. Or any other solutions. 

**Describe alternatives you've considered**

Any way for me to select CTI file.

**Additional context**

**Comment by EmmanuelP** [comment]
Hi @garfeng 

Aravis uses its own transport implementation, with no support for an external one.

I have little interest in trying to make Aravis use proprietary transport implementations. CTIs mainly exist because manufacturers artificially limit their implementation to their own devices, while Aravis is manufacturer agnostic.

That being said, if someone proposes a patch that implements this support, as long as it optional, and implemented in Aravis as ArvDevice, ArvInterface and  ArvStream subclasses, I will gladly accept it.

**Comment by garfeng** [comment]
Thank you very much  @EmmanuelP !

I researched the SDK provided by the manufacturer today and feel that if I use it, it will be difficult to switch to other brands of hardware in the future
That is, Aravis is better for me, reliable and open source.
Thank you very much again for your excellent work !
